# Basic python

# spilt this string

In [5]:
s="Hi there sam!"
s.split()


['Hi', 'there', 'sam!']

# 2. use.format() to print the following string

# output should be:The diameter of earth is 12742 kilometers

In [6]:
planet="Earth"
diameter="12742"
print("The diameter of{} is {} kilometers.".format(planet,diameter))

The diameter ofEarth is 12742 kilometers.


# 3.In this nest dictionary grab the word "hello"

In [10]:
d= {'k1':[1,2,3,{'trichy':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [11]:
d ['k1'][3]['trichy'][3]['target'][3]

'hello'

# Numpy

# 4.1 create an array of 10 zeros?

In [22]:
import numpy as np

In [21]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## 4.2 create an array of 10 fives?

In [24]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

# 5. Create an array of all even integer from 20 to 35

In [27]:
print(np.arange(20,36,2))

[20 22 24 26 28 30 32 34]


### 6. create a 3x3 matrix with values  ranging from 0 to 8

In [28]:
np.arange(0,9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# 7. concatinate a and b

### a= np.array([1,2,3]), b= np.array([4,5,6]) 

In [24]:
a= np.array([1,2,3])
b= np.array([4,5,6])
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])

# Pandas

#### 8. Create a dataframe with 3 rows and 2 coumns

In [4]:
import pandas as pd 

In [15]:
data={'name':['tom','jerry','sam'],
     'age':[15,12,14]}

pd.DataFrame(data)

name  age
0    tom   15
1  jerry   12
2    sam   14

## 9. Generate the series of data from 1st Jan,2022 to 10th Feb,2023

In [17]:
import  datetime

In [20]:
pd.to_datetime(pd.Series(["Jan 1,2022","2023-02-10",]))

0   2022-01-01
1   2023-02-10
dtype: datetime64[ns]

# 10.Create 2D list DataFrame

lists=[[1,'aaa',22],[2,'bbb',25],[3,'ccc',24]]

In [5]:
lists=[[1,'aaa',22],[2,'bbb',25],[3,'ccc',24]]
pd.DataFrame(lists)

0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24